### ISSUE TITLE
Type generations form GraphQL schema

### ISSUE THREAD

**Issue by sionelt** [sionelt/personal-finance-tracker#14]
#### Tasks:

- [x] Generate Typescript types from GraphQL schema.
- [x] Split schema and resolvers by domain.
- [x] Add initial schema and resolvers for User

**Comment by sionelt** [comment]
PR #17
