### ISSUE TITLE
Auth with GraphQL

### ISSUE THREAD

**Issue by sionelt** [sionelt/personal-finance-tracker#15]
#### Tasks:

- [ ] Setup password cryption with bcrupt
- [ ] Setup sign in token with JWT
- [ ] Persist password to db
